apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alert-analyzer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alert-analyzer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "alert-analyzer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alert-analyzer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: alert-analyzer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "alert-analyzer.fullname" . }}-config
            - secretRef:
                name: {{ include "alert-analyzer.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
